# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src//region.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Region(object):
    def setupUi(self, Region):
        Region.setObjectName("Region")
        Region.resize(300, 100)
        Region.setMinimumSize(QtCore.QSize(300, 100))
        Region.setMaximumSize(QtCore.QSize(16777215, 100))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Region)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Region)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editingRadio = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editingRadio.sizePolicy().hasHeightForWidth())
        self.editingRadio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.editingRadio.setFont(font)
        self.editingRadio.setChecked(True)
        self.editingRadio.setObjectName("editingRadio")
        self.horizontalLayout_2.addWidget(self.editingRadio)
        self.verticalWidget = QtWidgets.QWidget(self.frame)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calculateButton = QtWidgets.QPushButton(self.verticalWidget)
        self.calculateButton.setObjectName("calculateButton")
        self.verticalLayout.addWidget(self.calculateButton)
        self.deleteButton = QtWidgets.QPushButton(self.verticalWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)
        self.horizontalLayout_2.addWidget(self.verticalWidget)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Region)
        QtCore.QMetaObject.connectSlotsByName(Region)

    def retranslateUi(self, Region):
        _translate = QtCore.QCoreApplication.translate
        Region.setWindowTitle(_translate("Region", "Region"))
        self.editingRadio.setText(_translate("Region", "0"))
        self.calculateButton.setText(_translate("Region", "Расчитать"))
        self.deleteButton.setText(_translate("Region", "Удалить"))
